name: Scheduled Render Deploy

on:
  schedule:
    - cron: '*/15 * * * *'  # UTCで15分おき（JSTなら+9時間）

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy Hook
        run: curl -X POST https://render.com/deploy/YOUR_HOOK_ID
